In [1]:
import numpy as np

In [ ]:
	origins = ['I-House Berkeley',
               '51 California Ave San Francisco, CA 94130',
               '135 Fisher Loop San Francisco CA 94129',
               '2222 Broadway St San Francisco, CA 94115',
               '2007 Franklin St San Francisco, CA 94109',
              '465 California St San Francisco, CA 94104',
               'The Embarcadero & Folsom Street San Francisco, CA 94117',
               '2107 Lyon St San Francisco, CA 94115',
               '1 Dr Carlton B Goodlett Pl San Francisco, CA 94102',
               '100 John F Kennedy Dr San Francisco, CA 94118',
               '55 Music Concourse Dr San Francisco, CA 94118',
               '335 Martin Luther King Jr Dr San Francisco, CA 94118',
               '2128 Folsom St San Francisco, CA 94110',
               'Dolores St & 19th St San Francisco, CA 94114',
               'Sloat Blvd San Francisco, CA 94132']
	destinations = ['I-House Berkeley',
               '51 California Ave San Francisco, CA 94130',
               '135 Fisher Loop San Francisco CA 94129',
               '2222 Broadway St San Francisco, CA 94115',
               '2007 Franklin St San Francisco, CA 94109',
              '465 California St San Francisco, CA 94104',
               'The Embarcadero & Folsom Street San Francisco, CA 94117',
               '2107 Lyon St San Francisco, CA 94115',
               '1 Dr Carlton B Goodlett Pl San Francisco, CA 94102',
               '100 John F Kennedy Dr San Francisco, CA 94118',
               '55 Music Concourse Dr San Francisco, CA 94118',
               '335 Martin Luther King Jr Dr San Francisco, CA 94118',
               '2128 Folsom St San Francisco, CA 94110',
               'Dolores St & 19th St San Francisco, CA 94114',
               'Sloat Blvd San Francisco, CA 94132']

In [2]:
import json
import requests
import sys

if __name__ == '__main__':
	
	# The API key must be provided on the command line, abort otherwise. 
	api_key = 'AIzaSyCex-VuXIpsL73Etp9nbBV-afnwS1lgnnM'
	if len(sys.argv) != 2:
		print('Usage: distances.py <AIzaSyCex-VuXIpsL73Etp9nbBV-afnwS1lgnnM>')
		exit(1)
	else:
		api_key = sys.argv[1]

	# Google Distance Matrix base URL to which all other parameters are attached
	base_url = 'https://maps.googleapis.com/maps/api/distancematrix/json?'

    #Number 8 and 9 are the same
	# Google Distance Matrix domain-specific terms: origins and destinations
	origins = ['I-House Berkeley',
               '51 California Ave San Francisco, CA 94130',
               '135 Fisher Loop San Francisco CA 94129',
               '2222 Broadway St San Francisco, CA 94115',
               '2007 Franklin St San Francisco, CA 94109',
              '465 California St San Francisco, CA 94104',
               'The Embarcadero & Folsom Street San Francisco, CA 94117',
               '2107 Lyon St San Francisco, CA 94115',
               '1 Dr Carlton B Goodlett Pl San Francisco, CA 94102',
               '100 John F Kennedy Dr San Francisco, CA 94118']
	destinations = ['I-House Berkeley',
               '51 California Ave San Francisco, CA 94130',
               '135 Fisher Loop San Francisco CA 94129',
               '2222 Broadway St San Francisco, CA 94115',
               '2007 Franklin St San Francisco, CA 94109',
              '465 California St San Francisco, CA 94104',
               'The Embarcadero & Folsom Street San Francisco, CA 94117',
               '2107 Lyon St San Francisco, CA 94115',
               '1 Dr Carlton B Goodlett Pl San Francisco, CA 94102',
               '100 John F Kennedy Dr San Francisco, CA 94118']

	# Prepare the request details for the assembly into a request URL
	payload = {
		'origins' : '|'.join(origins),
		'destinations' : '|'.join(destinations), 
		'mode' : 'driving',
		'api_key' : api_key
	}

	# Assemble the URL and query the web service
	r = requests.get(base_url, params = payload)

	# Check the HTTP status code returned by the server. Only process the response, 
	# if the status code is 200 (OK in HTTP terms).
	if r.status_code != 200:
		print('HTTP status code {} received, program terminated.'.format(r.status_code))
	else:
		try:
			# Try/catch block should capture the problems when loading JSON data, 
			# such as when JSON is broken. It won't, however, help much if JSON format
			# for this service has changed -- in that case, the dictionaries json.loads() produces
			# may not have some of the fields queried later. In a production system, some sort
			# of verification of JSON file structure is required before processing it. In XML
			# this role is performed by XML Schema.
			x = json.loads(r.text)

			# Now you can do as you please with the data structure stored in x.
			# Here, we print it as a Cartesian product.
			for isrc, src in enumerate(x['origin_addresses']):
				for idst, dst in enumerate(x['destination_addresses']):
					row = x['rows'][isrc]
					cell = row['elements'][idst]
					if cell['status'] == 'OK':
						print('{} to {}: {}, {}.'.format(src, dst, cell['distance']['text'], cell['duration']['text']))
					else:
						print('{} to {}: status = {}'.format(src, dst, cell['status']))

			# Of course, we could have also saved the results in a file,
			with open('gdmpydemo.json', 'w') as f:
				f.write(r.text)

			# TODO Or in a database,

			# Or whatever.
			# ???
			# Profit!

		except ValueError:
			print('Error while parsing JSON response, program terminated.')

	# Prepare for debugging, but only if interactive. Now you can pprint(x), for example.
	if sys.flags.interactive:
		from pprint import pprint

Usage: distances.py <AIzaSyCex-VuXIpsL73Etp9nbBV-afnwS1lgnnM>
International House, 2299 Piedmont Ave, Berkeley, CA 94720, USA to International House, 2299 Piedmont Ave, Berkeley, CA 94720, USA: 1 m, 1 min.
International House, 2299 Piedmont Ave, Berkeley, CA 94720, USA to 51 California Ave, San Francisco, CA 94130, USA: 15.9 km, 21 mins.
International House, 2299 Piedmont Ave, Berkeley, CA 94720, USA to 135 Fisher Loop, San Francisco, CA 94129, USA: 26.8 km, 44 mins.
International House, 2299 Piedmont Ave, Berkeley, CA 94720, USA to 2222 Broadway, San Francisco, CA 94115, USA: 23.5 km, 37 mins.
International House, 2299 Piedmont Ave, Berkeley, CA 94720, USA to 2007 Franklin St, San Francisco, CA 94109, USA: 22.4 km, 34 mins.
International House, 2299 Piedmont Ave, Berkeley, CA 94720, USA to 465 California St, San Francisco, CA 94104, USA: 20.1 km, 26 mins.
International House, 2299 Piedmont Ave, Berkeley, CA 94720, USA to Folsom St & The Embarcadero, San Francisco, CA 94105, USA: 19.8 

In [5]:
x

{u'destination_addresses': [u'International House, 2299 Piedmont Ave, Berkeley, CA 94720, USA',
  u'51 California Ave, San Francisco, CA 94130, USA',
  u'135 Fisher Loop, San Francisco, CA 94129, USA',
  u'2222 Broadway, San Francisco, CA 94115, USA',
  u'2007 Franklin St, San Francisco, CA 94109, USA',
  u'465 California St, San Francisco, CA 94104, USA',
  u'Folsom St & The Embarcadero, San Francisco, CA 94105, USA',
  u'2107 Lyon St, San Francisco, CA 94115, USA',
  u'1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102, USA',
  u'100 John F Kennedy Dr, San Francisco, CA 94118, USA'],
 u'origin_addresses': [u'International House, 2299 Piedmont Ave, Berkeley, CA 94720, USA',
  u'51 California Ave, San Francisco, CA 94130, USA',
  u'135 Fisher Loop, San Francisco, CA 94129, USA',
  u'2222 Broadway, San Francisco, CA 94115, USA',
  u'2007 Franklin St, San Francisco, CA 94109, USA',
  u'465 California St, San Francisco, CA 94104, USA',
  u'Folsom St & The Embarcadero, San Francisco, CA 9

In [6]:
from ortools.constraint_solver import pywrapcp
from ortools.constraint_solver import routing_enums_pb2

# Distance callback
class CreateDistanceCallback(object):
  """Create callback to calculate distances between points."""
  def __init__(self):
    """Array of distances between points."""

    self.matrix = [[0 , 15.9, 26.8, 23.5, 22.4, 20.1, 19.8, 24.3, 21.8, 26.2],
             [16.6, 0, 13.2, 9.8, 8.8, 6.5, 6.1, 10.7, 8.1, 12.5],
             [29.2, 15.6, 0, 3.5, 4.5, 6.7, 7.9, 2.5, 6.3, 3.9],
             [23.2, 9.5, 3.5, 0, 1.1, 3.2, 4.4, 1.4, 3.0, 4.9],
             [22.6, 9, 4.5, 1, 0, 2.6, 3.9, 2.0, 2.3, 5.4],
             [19.8, 6.2, 6.9, 3.3, 2.3, 0, 1.4, 4.4, 2.9, 6.9],
             [19.3, 5.7, 7.9, 4.4, 3.7, 1.4, 0, 5.8, 4.1, 8.4],
             [26.8,13.1, 2.5, 1.4, 2.6, 4.6, 5.8, 0, 3.8, 3.4],
             [22.1, 8.4, 6.3, 2.9, 1.9, 2.9, 4.6, 3.8, 0, 4.1],
             [26.1, 12.4, 3.9, 4.8, 5.3, 6.9, 8.6, 3.4, 4.2, 0]]
    
    
  def Distance(self, from_node, to_node):
    return int(self.matrix[from_node][to_node])
def main():

  # Cities
  city_names = ["I-House", "Treasure Island Chapel", "Golden Gate Club", "Flood Mansion", "Haas-Lilienthal House", "The Julia Morgan Ballroom", "Cupid's Span",
                "Swedenborgian Church", "San Francisco City Hall, the Rotunda and San Francisco City Hall, Fourth Floor and ", "Conservatory of Flowers"]
  tsp_size = len(city_names)
  num_routes = 1    # The number of routes, which is 1 in the TSP.
  # Nodes are indexed from 0 to tsp_size - 1. The depot is the starting node of the route.
  depot = 0

  # Create routing model
  if tsp_size > 0:
    routing = pywrapcp.RoutingModel(tsp_size, num_routes, depot)
    search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()

    # Create the distance callback, which takes two arguments (the from and to node indices)
    # and returns the distance between these nodes.
    dist_between_nodes = CreateDistanceCallback()
    dist_callback = dist_between_nodes.Distance
    routing.SetArcCostEvaluatorOfAllVehicles(dist_callback)
    # Solve, returns a solution if any.
    assignment = routing.SolveWithParameters(search_parameters)
    if assignment:
      # Solution cost.
      print "Total distance: " + str(assignment.ObjectiveValue()) + " km\n"
      # Inspect solution.
      # Only one route here; otherwise iterate from 0 to routing.vehicles() - 1
      route_number = 0
      index = routing.Start(route_number) # Index of the variable for the starting node.
      route = ''
      while not routing.IsEnd(index):
        # Convert variable indices to node indices in the displayed route.
        route += str(city_names[routing.IndexToNode(index)]) + ' -> '
        index = assignment.Value(routing.NextVar(index))
      route += str(city_names[routing.IndexToNode(index)])
      print "Route:\n\n" + route
    else:
      print 'No solution found.'
  else:
    print 'Specify an instance greater than 0.'

if __name__ == '__main__':
  main()

Total distance: 56 km

Route:

I-House -> Treasure Island Chapel -> Haas-Lilienthal House -> Flood Mansion -> Swedenborgian Church -> Golden Gate Club -> Conservatory of Flowers -> San Francisco City Hall, the Rotunda and San Francisco City Hall, Fourth Floor and  -> The Julia Morgan Ballroom -> Cupid's Span -> I-House


In [71]:
len([0 , 15.9, 26.8, 23.5, 22.4, 20.1, 19.8, 24.3, 21.8, 26.2])

10

In [72]:
len([16.6, 0, 13.2, 9.8, 8.8, 6.5, 6.1, 10.7, 8.1, 12.5])

10

In [73]:
len([29.2, 15.6, 0, 3.5, 4.5, 6.7, 7.9, 2.5, 6.3, 3.9])

10

In [74]:
len([23.2, 9.5, 3.5, 0, 1.1, 3.2, 4.4, 1.4, 3.0, 4.9])

10

In [75]:
len([22.6, 9, 4.5, 1, 0, 2.6, 3.9, 2.0, 2.3, 5.4])

10

In [76]:
len([19.8, 6.2, 6.9, 3.3, 2.3, 0, 1.4, 4.4, 2.9, 6.9])

10

In [77]:
len([19.3, 5.7, 7.9, 4.4, 3.7, 1.4, 0, 5.8, 4.1, 8.4])

10

In [78]:
len([26.8,13.1, 2.5, 1.4, 2.6, 4.6, 5.8, 0, 3.8, 3.4])

10

In [79]:
len([22.1, 8.4, 6.3, 2.9, 1.9, 2.9, 4.6, 3.8, 0, 4.1])

10

In [80]:
len([26.1, 12.4, 3.9, 4.8, 5.3, 6.9, 8.6, 3.4, 4.2, 0])

10

In [10]:
a=[[0 , 15.9, 26.8, 23.5, 22.4, 20.1, 19.8, 24.3, 21.8, 26.2],
             [16.6, 0, 13.2, 9.8, 8.8, 6.5, 6.1, 10.7, 8.1, 12.5],
             [29.2, 15.6, 0, 3.5, 4.5, 6.7, 7.9, 2.5, 6.3, 3.9],
             [23.2, 9.5, 3.5, 0, 1.1, 3.2, 4.4, 1.4, 3.0, 4.9],
             [22.6, 9, 4.5, 1, 0, 2.6, 3.9, 2.0, 2.3, 5.4],
             [19.8, 6.2, 6.9, 3.3, 2.3, 0, 1.4, 4.4, 2.9, 6.9],
             [19.3, 5.7, 7.9, 4.4, 3.7, 1.4, 0, 5.8, 4.1, 8.4],
             [26.8,13.1, 2.5, 1.4, 2.6, 4.6, 5.8, 0, 3.8, 3.4],
             [22.1, 8.4, 6.3, 2.9, 1.9, 2.9, 4.6, 3.8, 0, 4.1],
             [26.1, 12.4, 3.9, 4.8, 5.3, 6.9, 8.6, 3.4, 4.2, 0]]

In [13]:
a=np.matrix(a)

In [87]:
print a

[[  0.   15.9  26.8  23.5  22.4  20.1  19.8  24.3  21.8  26.2]
 [ 16.6   0.   13.2   9.8   8.8   6.5   6.1  10.7   8.1  12.5]
 [ 29.2  15.6   0.    3.5   4.5   6.7   7.9   2.5   6.3   3.9]
 [ 23.2   9.5   3.5   0.    1.1   3.2   4.4   1.4   3.    4.9]
 [ 22.6   9.    4.5   1.    0.    2.6   3.9   2.    2.3   5.4]
 [ 19.8   6.2   6.9   3.3   2.3   0.    1.4   4.4   2.9   6.9]
 [ 19.3   5.7   7.9   4.4   3.7   1.4   0.    5.8   4.1   8.4]
 [ 26.8  13.1   2.5   1.4   2.6   4.6   5.8   0.    3.8   3.4]
 [ 22.1   8.4   6.3   2.9   1.9   2.9   4.6   3.8   0.    4.1]
 [ 26.1  12.4   3.9   4.8   5.3   6.9   8.6   3.4   4.2   0. ]]


In [88]:
a.shape

(10, 10)

In [15]:
def distance(lat1, long1, lat2, long2):
    # Note: The formula used in this function is not exact, as it assumes
    # the Earth is a perfect sphere.

    # Mean radius of Earth in miles
    radius_earth = 3959

    # Convert latitude and longitude to
    # spherical coordinates in radians.
    degrees_to_radians = math.pi/180.0
    phi1 = lat1 * degrees_to_radians
    phi2 = lat2 * degrees_to_radians
    lambda1 = long1 * degrees_to_radians
    lambda2 = long2 * degrees_to_radians
    dphi = phi2 - phi1
    dlambda = lambda2 - lambda1

    a = haversine(dphi) + math.cos(phi1) * math.cos(phi2) * haversine(dlambda)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    d = radius_earth * c
    return d

def haversine(angle):
  h = math.sin(angle / 2) ** 2
  return h

 # With the latitude longitude

In [16]:
import math
from ortools.constraint_solver import pywrapcp
from ortools.constraint_solver import routing_enums_pb2


# Distance callback

class CreateDistanceCallback(object):
  """Create callback to calculate distances between points."""

  def __init__(self):

    # Latitudes and longitudes of selected U.S. cities

    locations = [[37.869656,  -122.251430], # I House
                 [37.818072, -122.372164],    #1
                 [37.800404, -122.461499], # 2
                 [37.794720,  -122.433990], # 3
                 [37.793299,  -122.424981], # 4
                 [37.792682, -122.402161], # 5
                 [37.790751,  -122.390145], # 6
                 [37.790409, -122.446261], # 7
                 [37.779050, -122.418853], # 8 and 9
                 [37.772619, -122.460256], # 10
                # [37.769822, -122.466008], # 11
                # [37.768761 , -122.467979], # 12
                # [37.763235 , -122.415341], # 13
                # [37.759825 , -122.426019], # 14
                # [37.734030 , -122.489182], # 15
                 ] 

    """Create the distance matrix."""
    size = len(locations)
    self.matrix = {}

    for from_node in xrange(size):
      self.matrix[from_node] = {}
      for to_node in xrange(size):
        if from_node == to_node:
          self.matrix[from_node][to_node] = 0
        else:
          x1 = locations[from_node][0]
          y1 = locations[from_node][1]
          x2 = locations[to_node][0]
          y2 = locations[to_node][1]
          self.matrix[from_node][to_node] = distance(x1, y1, x2, y2)

  def Distance(self, from_node, to_node):
    return int(self.matrix[from_node][to_node])

def main():

  # Cities
  #city_names = ["I-House", "Los Angeles", "Chicago", "Minneapolis", "Denver", "Dallas", "Seattle",
   #             "Boston", "San Francisco", "St. Louis", "Houston", "Phoenix", "Salt Lake City"]

  city_names = ["I-House",
                "Treasure Island Chapel", 
                  "Golden Gate Club", 
                  "Flood Mansion", 
                  "Haas-Lilienthal House", 
                  "The Julia Morgan Ballroom", 
                  "Cupid's Span", 
                  "Swedenborgian Church", 
                  "San Francisco City Hall, the Rotunda and San Francisco City Hall, Fourth Floor",
                  "Conservatory of Flowers",
                 # "California Academy of Sciences",
                 # "Shakespeare Garden",
                 # "Stable Cafe",
                 # "Mission Dolores Park",
                 # "Stern Grove Trocadero Clubhouse",
                      ]
    
  tsp_size = len(city_names)
  num_routes = 1    # The number of routes, which is 1 in the TSP.
  # Nodes are indexed from 0 to tsp_size - 1. The depot is the starting node of the route.
  depot = 0

  # Create routing model
  if tsp_size > 0:
    routing = pywrapcp.RoutingModel(tsp_size, num_routes, depot)
    search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()

    # Create the distance callback, which takes two arguments (the from and to node indices)
    # and returns the distance between these nodes.
    dist_between_nodes = CreateDistanceCallback()
    dist_callback = dist_between_nodes.Distance
    routing.SetArcCostEvaluatorOfAllVehicles(dist_callback)
    # Solve, returns a solution if any.
    assignment = routing.SolveWithParameters(search_parameters)
    if assignment:
      # Solution cost.
      print "Total distance: " + str(assignment.ObjectiveValue()) + " km\n"
      # Inspect solution.
      # Only one route here; otherwise iterate from 0 to routing.vehicles() - 1
      route_number = 0
      index = routing.Start(route_number) # Index of the variable for the starting node.
      route = ''
      while not routing.IsEnd(index):
        # Convert variable indices to node indices in the displayed route.
        route += str(city_names[routing.IndexToNode(index)]) + ' -> '
        index = assignment.Value(routing.NextVar(index))
      route += str(city_names[routing.IndexToNode(index)])
      print "Route:\n\n" + route
    else:
      print 'No solution found.'
  else:
    print 'Specify an instance greater than 0.'

if __name__ == '__main__':
  main()

Total distance: 24 km

Route:

I-House -> Treasure Island Chapel -> Cupid's Span -> The Julia Morgan Ballroom -> San Francisco City Hall, the Rotunda and San Francisco City Hall, Fourth Floor -> Golden Gate Club -> Conservatory of Flowers -> Swedenborgian Church -> Flood Mansion -> Haas-Lilienthal House -> I-House
